import 'dart:math' as math;
import 'package:supabase_flutter/supabase_flutter.dart';
import 'models/address.dart';

class AddressesService {
  final SupabaseClient _supabase = Supabase.instance.client;

  Future<List<Address>> getAddresses(String userId) async {
    final response = await _supabase
        .from('addresses')
        .select()
        .eq('user_id', userId)
        .order('is_default', ascending: false)
        .order('created_at', ascending: false);

    return (response as List).map((json) => Address.fromJson(json)).toList();
  }

  Future<Address?> getDefaultAddress(String userId) async {
    final response = await _supabase
        .from('addresses')
        .select()
        .eq('user_id', userId)
        .eq('is_default', true)
        .maybeSingle();

    if (response == null) return null;
    return Address.fromJson(response);
  }

  Future<Address> createAddress(Address address) async {
    final data = address.toJson();
    // Remove fields that should be auto-generated by database
    data.remove('id');
    data.remove('created_at');
    data.remove('updated_at');

    final response = await _supabase
        .from('addresses')
        .insert(data)
        .select()
        .single();

    return Address.fromJson(response);
  }

  Future<Address> updateAddress(Address address) async {
    if (address.id == null) {
      throw Exception('Cannot update address without id');
    }

    final data = address.toJson();
    // Don't update auto-managed timestamps
    data.remove('created_at');
    data.remove('updated_at');
    data.remove('id'); // Don't update the id

    final response = await _supabase
        .from('addresses')
        .update(data)
        .eq('id', address.id!)
        .select()
        .single();

    return Address.fromJson(response);
  }

  Future<void> deleteAddress(String addressId) async {
    await _supabase.from('addresses').delete().eq('id', addressId);
  }

  Future<void> setDefaultAddress(String userId, String addressId) async {
    // Unset all defaults
    await _unsetDefaultAddresses(userId);

    // Set new default
    await _supabase
        .from('addresses')
        .update({'is_default': true})
        .eq('id', addressId);
  }

  Future<void> _unsetDefaultAddresses(String userId) async {
    await _supabase
        .from('addresses')
        .update({'is_default': false})
        .eq('user_id', userId)
        .eq('is_default', true);
  }

  Future<Address?> findNearestAddress(
    String userId,
    double latitude,
    double longitude,
  ) async {
    final addresses = await getAddresses(userId);
    
    if (addresses.isEmpty) return null;

    Address? nearest;
    double minDistance = double.infinity;

    for (final address in addresses) {
      final distance = _calculateDistance(
        latitude,
        longitude,
        address.latitude,
        address.longitude,
      );

      if (distance < minDistance) {
        minDistance = distance;
        nearest = address;
      }
    }

    // Only return if within 1km
    if (minDistance <= 1.0) {
      return nearest;
    }

    return null;
  }

  double _calculateDistance(
    double lat1,
    double lon1,
    double lat2,
    double lon2,
  ) {
    // Using Haversine formula
    const double earthRadius = 6371.0; // km
    
    final dLat = _toRadians(lat2 - lat1);
    final dLon = _toRadians(lon2 - lon1);
    final lat1Rad = _toRadians(lat1);
    final lat2Rad = _toRadians(lat2);

    final a = math.sin(dLat / 2) * math.sin(dLat / 2) +
        math.cos(lat1Rad) *
            math.cos(lat2Rad) *
            math.sin(dLon / 2) *
            math.sin(dLon / 2);

    final c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a));
    return earthRadius * c;
  }

  double _toRadians(double degrees) {
    return degrees * math.pi / 180.0;
  }
}

